version: '3.8'

services:
  raccoon-server:
    build: ./server
    container_name: raccoon-vulnerable-server
    ports:
      - "3000:80"    # HTTP accessible sur localhost:3000
      - "8443:443"  # HTTPS vulnérable sur localhost:8443
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: unless-stopped
    networks:
      - raccoon-net

  # Client de test optionnel
  raccoon-client:
    image: alpine:latest
    container_name: raccoon-test-client
    depends_on:
      - raccoon-server
    command: |
      sh -c "
        apk add --no-cache curl openssl &&
        echo 'Client de test prêt. Utilisez docker exec pour exécuter des commandes.' &&
        tail -f /dev/null
      "
    networks:
      - raccoon-net

networks:
  raccoon-net:
    driver: bridge

volumes:
  logs: